name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
        run: echo $GOOGLE_APPLICATION_CREDENTIALS > firebase_api_key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: private_files/firebase_api_key.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
